language: ruby
cache: bundler
rvm:
  - 2.4.5
before_install: gem install bundler -v 1.16.1

install: bundle install --jobs=3 --retry=3 --deployment --without development
addons:
    code_climate:
        repo_token: 8a2a969cd1d481fbc952943cc27b54584b2f27217ea2e2905e77652d44c502be
before_script:
  - mysql -e 'create database myapp_test;'
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.travis.yml config/secrets.yml
  - cp config/rabbitmq.travis.yml config/rabbitmq.yml
services:
  - mysql
  - rabbitmq
script:  
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake db:seed
  - RAILS_ENV=test bundle exec rspec spec/
  - RAILS_ENV=test bundle exec cucumber
